In [4]:
import pandas as pd
import numpy as np
import json
import sys
sys.path.append("../")
PATH = "../.."

In [5]:
''' Load data '''

with open(f"{PATH}/data/data_dtypes.json", "r") as f:
    dtypes = json.load(f)

In [7]:
''' all variables '''
df_all = pd.read_csv(f"{PATH}/data/fullRegistry.csv", index_col=0, dtype=dtypes)
print(df_all.shape)





''' histologie subgroup '''
df_hist = pd.read_csv(f"{PATH}/data/histologie_subgroup.csv", index_col=0, dtype=dtypes)

# #### Paolo left "histologie" inside - remove cause obsolete!
# df_hist = df_hist.drop(["histologie_sprb"], axis=1)
# df_hist.to_csv(f"{PATH}/data/histologie_subgroup.csv")

print(df_hist.shape)





''' natural variables'''
df_natural = pd.read_csv(f"{PATH}/data/natural.csv", index_col=0, dtype=dtypes)

# #### Paolo forgot the "gender" variable here - fix that!
# df_natural = pd.concat([df_natural, df_all["gender"]], axis=1)
# df_natural.to_csv(f"{PATH}/data/natural_variables.csv")

print(df_natural.shape)

(1814, 39)
(618, 40)
(1814, 17)

In [20]:
df_hist

,gender,zn_myasthener_krise_jn,zn_myasthener_exazerbation,aktueller_mgfa_score,mgfaklassifikation_schlimmste_historisch_rb,okulaer,bulbaer,generalisiertemuskelschwaeche,muskelschmerz,autoimmunerkrankungen_rbzu,...,ivig_sprb,age,age_erstmanifestation,age_bei_diagnose,Diagnosedauer,scoreqmg_neu,scoreqol_neu,scoreadl_neu,chronicfatigue_neu,seelischesbefinden_neu
pid,,,,,,,,,,,,,,,,,,,,,
0X13811D,1.0,0.0,0.0,0,2,1.0,0.0,1.0,1.0,NaN,...,0.0,60.0,39.0,41.0,2.0,NaN,NaN,15.0,11.0,11.0
01M51DX3,0.0,0.0,0.0,NaN,2,0.0,0.0,1.0,0.0,NaN,...,0.0,39.0,16.0,NaN,NaN,7.0,20.0,0.0,NaN,NaN
05929E6J,1.0,0.0,0.0,NaN,4,1.0,0.0,1.0,0.0,0.0,...,0.0,30.0,28.0,30.0,2.0,8.0,NaN,7.0,NaN,NaN
0CZYEHJ3,1.0,0.0,0.0,3,5,1.0,1.0,1.0,0.0,1.0,...,0.0,37.0,35.0,35.0,0.0,NaN,3.0,0.0,17.0,2.0
0LW74ZFX,1.0,0.0,0.0,NaN,NaN,1.0,0.0,1.0,0.0,0.0,...,1.0,54.0,16.0,32.0,16.0,NaN,26.0,10.0,26.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YPP9HWKL,1.0,0.0,0.0,NaN,2,1.0,0.0,1.0,0.0,0.0,...,0.0,39.0,20.0,21.0,1.0,NaN,15.0,4.0,15.0,6.0
YUUDGU7Y,1.0,0.0,0.0,NaN,1,1.0,0.0,0.0,0.0,0.0,...,0.0,61.0,NaN,58.0,NaN,NaN,4.0,2.0,12.0,6.0
ZADM8GU6,1.0,0.0,0.0,NaN,5,1.0,1.0,1.0,NaN,0.0,...,0.0,75.0,72.0,72.0,0.0,NaN,NaN,7.0,NaN,NaN
ZQ13VWFK,0.0,0.0,0.0,NaN,3,1.0,0.0,0.0,0.0,0.0,...,0.0,78.0,NaN,78.0,NaN,NaN,41.0,NaN,23.0,23.0
ZT72JD0X,0.0,0.0,0.0,NaN,5,1.0,1.0,1.0,1.0,0.0,...,0.0,60.0,NaN,57.0,NaN,NaN,40.0,4.0,NaN,NaN

## Old: Inverse gender (1=female, 0=male)

In [3]:
dic_gender = {1:0, 
              0:1}

data["gender"] = data["gender"].replace(dic_gender)

data.to_csv(f"{PATH}/data/all_data_edited_v3_mgfaRecoded_inverse.csv")

In [4]:
data["gender"].value_counts()

gender
1.0    1019
0.0     795
Name: count, dtype: int64

In [3]:
data

,gender,zn_myasthener_krise_jn,zn_myasthener_exazerbation,aktueller_mgfa_score,aktuelle_MGFA_umkodiert,mgfaklassifikation_schlimmste_historisch_rb,okulaer,bulbaer,generalisiertemuskelschwaeche,muskelschmerz,...,age,age_erstmanifestation,age_bei_diagnose,Diagnosedauer,seronegativ,scoreqmg_neu,scoreqol_neu,scoreadl_neu,chronicfatigue_neu,seelischesbefinden_neu
pid,,,,,,,,,,,,,,,,,,,,,
P7X50M0V,0.0,0.0,0.0,8,3,8,0.0,0.0,1.0,0.0,...,62.0,61.0,61.0,0.0,0.0,5.0,NaN,1.0,19.0,22.0
0X13811D,0.0,0.0,0.0,0,0,2,1.0,0.0,1.0,1.0,...,60.0,39.0,41.0,2.0,0.0,NaN,NaN,15.0,11.0,11.0
002D7Y7Z,0.0,0.0,0.0,3,3,3,1.0,1.0,1.0,1.0,...,60.0,54.0,57.0,3.0,0.0,NaN,32.0,9.0,21.0,22.0
002G71A3,1.0,0.0,0.0,NaN,NaN,1,1.0,0.0,0.0,0.0,...,64.0,64.0,64.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN
00C4EK1J,1.0,0.0,0.0,1,1,3,1.0,1.0,0.0,0.0,...,82.0,NaN,73.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWUVEM64,1.0,0.0,0.0,3,3,3,1.0,0.0,0.0,0.0,...,60.0,58.0,58.0,0.0,0.0,NaN,3.0,0.0,13.0,3.0
ZXX7E4X4,0.0,0.0,0.0,NaN,NaN,2,NaN,NaN,NaN,NaN,...,58.0,45.0,45.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
ZY91U2Q2,0.0,0.0,0.0,NaN,NaN,1,NaN,NaN,NaN,NaN,...,68.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
ZZEHZKCR,0.0,0.0,0.0,0,0,2,1.0,1.0,1.0,0.0,...,32.0,18.0,19.0,1.0,0.0,NaN,0.0,NaN,13.0,0.0
ZZZ1Y1R6,1.0,0.0,0.0,3,3,3,1.0,0.0,0.0,NaN,...,25.0,24.0,24.0,0.0,1.0,NaN,16.0,6.0,NaN,NaN

In [4]:
data["see"]

Index(['gender', 'zn_myasthener_krise_jn', 'zn_myasthener_exazerbation',
       'aktueller_mgfa_score', 'aktuelle_MGFA_umkodiert',
       'mgfaklassifikation_schlimmste_historisch_rb', 'okulaer', 'bulbaer',
       'generalisiertemuskelschwaeche', 'muskelschmerz',
       'autoimmunerkrankungen_rbzu', 'testergebnisdekrement_rb',
       'testergebnispyridostigmin_rb', 'achrak_rb', 'antimuskak_rb',
       'lrp4antikoerper_rb', 'thymektomie_gr', 'histologie_sprb',
       'pyridostigmin_sprb', 'immuntherapie_grrb', 'kortison_sprb',
       'azathioprin_sprb', 'methotrexatfolsauure_sprb',
       'mycophenolatmofetil_sprb',
       'eskalationstherapiebeitherapierefraktaerermyasthenie_grrb',
       'eculizumab_sprb', 'rituximab_sprb', 'exazerbationstherapie_grrb',
       'plasmapherese_sprb', 'immunadsorption_sprb', 'ivig_sprb', 'age',
       'age_erstmanifestation', 'age_bei_diagnose', 'Diagnosedauer',
       'seronegativ', 'scoreqmg_neu', 'scoreqol_neu', 'scoreadl_neu',
       'chronicfatigue_neu', 'seelischesbefinden_neu'],
      dtype='object')